name: Making a first workflow
run-name: i am making a workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:
    pull_request:
      branches:
        - main
      paths-ignore:
        - README.md
jobs: 
    Ejecutando-ESLint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install modules
          run: timeout 180s yarn
        - name: Run ESLint
          run: timeout 180s yarn run eslint .

    Consulta-Api:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: make post
          run: |
            timeout 180s curl -d '{"nombre": "Charizard","tipo": "Fuego","faseEvolucion": "Fase 2","puntosSalud": 120,"ataques": [{"nombre": "Lanzallamas","costoEnergia": ["Fuego", "Fuego", "Incolora"],"danio": "100","descripcion": "Quema al Pokémon Defensor"}]}' \
              -H "Content-type: application/json" \
              -X POST https://pokemon-api-vpmj.onrender.com/cards

    Update-version-date-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Make update script executable
          run: chmod +x .github/workflows/update_version.sh

        - name: Run update script
          run: timeout 180s .github/workflows/update_version.sh

        - name: Configure Git
          run: |
            git config --global user.name "GitHub Actions Bot"
            git config --global user.email "actions@github.com"

        - name: Commit and push changes
          run: |
            git add README.md
            git commit -m "Update README with new version"
            git push origin main

        - name: Make date script executable
          run: chmod +x .github/workflows/update_date.sh

        - name: Run date script
          run: timeout 180s .github/workflows/update_date.sh

        - name: Commit and push changes
          run: |
            git add README.md
            git commit -m "Update README with new date"
            git push origin main

      

